export const UPDATE_SCHEDULE_RAW = 'UPDATE_SCHEDULE_RAW';
export const UPDATE_SCHEDULE_RAW_STORAGE = 'UPDATE_SCHEDULE_RAW_STORAGE';
export const UPDATE_SCHEDULE_RAW_ALL = 'UPDATE_SCHEDULE_RAW_ALL';
export const UPDATE_SCHEDULE_RAW_COURSe_GROUP = 'UPDATE_SCHEDULE_RAW_COURSe_GROUP';
export const SET_SIMPLE_SCHEDULE = 'SET_SIMPLE_SCHEDULE';
